config/routes.rb
Rails.application.routes.draw do
  resources :books do
    member do
      get 'delete', to: 'books#delete'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
    validates :author, presence: true
    validates :price, presence: true
    validates :date_published, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
    @book = Book.find(params[:id])
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book } 
      else
        format.html do
          flash.now[:alert] = "Error creating the book."
          if @book.title.blank?
            format.html { redirect_to new_book_path, alert: "Title can't be blank." }
            format.json { render json: { errors: ["Title can't be blank."] }, status: :unprocessable_entity }
          end
          render :new, status: :unprocessable_entity
        end
        format.json { render json: { errors: @book.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @book = Book.find(params[:id])
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :price, :date_published)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/delete.html.erb
<%= link_to("Back to Books", books_path, class: 'back-link') %>

<div class="books delete">
  <h2>Delete Book</h2>

  <%= form_for(@book, method: 'delete') do |f| %>
    <% # url: book_path(@book), method: 'delete' %>

    <p>Are you sure you want to permanently delete this book?</p>
    <p><%= @book.title %></p>

    <div class="form-buttons">
      <%= f.submit("Delete book") %>
    </div>

  <% end %>
</div>

app/views/books/edit.html.erb
<%= link_to "Back to books", books_path %>

<h1>Editing book</h1>

<div class="books edit">
  <%= form_for(@book) do |f| %>
    <% # url: books_path(@book), method: 'patch' %>
    <table summary="Book form fields">
      <tr>
        <th><%= f.label :title %></th>
        <td><%= f.text_field :title %></td>
      </tr>
      <tr>
        <th><%= f.label :author %></th>
        <td><%= f.text_field :author %></td>
      </tr>
      <tr>
        <th><%= f.label :price %></th>
        <td><%= f.number_field :price, step: '0.01' %></td>
      </tr>
      <tr>
        <th><%= f.label :date_published %></th>
        <td><%= f.date_field :date_published %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Edit Book") %>
    </div>
    <% end %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books</h1>

<table class="listing" summary="Book list" style="width: 100%;">
  <tr class="header">
    <th>Title</th>
    <th>Author</th>
    <th>Price</th>
    <th>Date Published</th>
    <th>Show Details</th>
  </tr>
  <% @books.each do |book| %>
    <tr>
      <td style="text-align: center;"><%= book.title %></td>
      <td style="text-align: center;"><%= book.author %></td>
      <td style="text-align: center;"><%= book.price %></td>
      <td style="text-align: center;"><%= book.date_published.strftime("%m-%d-%Y") %></td>
      <td style="text-align: center;"><%= link_to "Show Details", book %></td>
    </tr>
  <% end %>
</table>

<%= link_to "New book", new_book_path %>

app/views/books/new.html.erb
<% flash.each do |type, message| %>
  <p style="color: <%= type == 'notice' ? 'green' : 'red' %>"><%= message %></p>
<% end %>

<div>
  <%= link_to "Back to books", books_path %>
</div>

<h1>New book</h1>

<div class="books new">
  <%= form_for(@book) do |f| %>
    <% # url: books_path, method: 'post' %>
    <table summary="Book form fields">
      <tr>
        <th><%= f.label :title %></th>
        <td><%= f.text_field :title %></td>
      </tr>
      <tr>
        <th><%= f.label :author %></th>
        <td><%= f.text_field :author %></td>
      </tr>
      <tr>
        <th><%= f.label :price %></th>
        <td><%= f.number_field :price, step: '0.01' %></td>
      </tr>
      <tr>
        <th><%= f.label :date_published %></th>
        <td><%= f.date_field :date_published %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Create Book") %>
    </div>
    <% end %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <%= link_to "Back to books", books_path %>
</div>

<h1>Details</h1>

<table summary="Book detail view">
    <tr>
      <th>Title</th>
      <td><%= @book.title %></td>
    </tr>
    <tr>
      <th>Author</th>
      <td><%= @book.author %></td>
    </tr>
    <tr>
      <th>Price</th>
      <td><%= @book.price %></td>
    </tr>
    <tr>
      <th>Date Published</th>
      <td><%= @book.date_published %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @book.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @book.updated_at %></td>
    </tr>
  </table>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> 
  <%= link_to "Delete this book", delete_book_path(@book) %> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>